"""Commonly impersonated brands: display name, name keywords, and domains the brand really owns.

Keywords are matched against the scanned domain's name. Add local banks or services here.
Leave out domains where anyone can publish (blogspot.com, googleusercontent.com, ...):
pages there aren't the brand.
"""

BRANDS: list[tuple[str, list[str], list[str]]] = [
    # payments & banking
    ("PayPal", ["paypal"], ["paypal.com", "paypal.me", "paypalobjects.com"]),
    ("Chase", ["chase"], ["chase.com", "jpmorganchase.com", "jpmorgan.com"]),
    ("Wells Fargo", ["wellsfargo"], ["wellsfargo.com", "wf.com"]),
    ("Bank of America", ["bankofamerica", "bofa"], ["bankofamerica.com", "bofa.com"]),
    ("Citibank", ["citibank"], ["citibank.com", "citi.com"]),
    ("HSBC", ["hsbc"], ["hsbc.com", "hsbc.co.uk", "hsbc.co.in"]),
    ("Barclays", ["barclays"], ["barclays.co.uk", "barclays.com"]),
    ("American Express", ["americanexpress", "amex"], ["americanexpress.com", "aexp.com"]),
    ("Capital One", ["capitalone"], ["capitalone.com"]),
    ("Visa", ["visa"], ["visa.com"]),
    ("Mastercard", ["mastercard"], ["mastercard.com"]),
    ("State Bank of India", ["onlinesbi", "sbi"], ["onlinesbi.sbi", "sbi.co.in", "onlinesbi.com", "sbi.bank.in"]),
    ("HDFC Bank", ["hdfcbank", "hdfc"], ["hdfcbank.com", "hdfc.com", "hdfcbank.bank.in"]),
    ("ICICI Bank", ["icicibank", "icici"], ["icicibank.com", "icici.com", "icici.bank.in"]),
    ("Axis Bank", ["axisbank"], ["axisbank.com", "axis.bank.in"]),
    ("Paytm", ["paytm"], ["paytm.com", "paytm.in"]),
    ("PhonePe", ["phonepe"], ["phonepe.com"]),
    ("Income Tax India", ["incometax", "incometaxindia"], ["incometax.gov.in", "incometaxindia.gov.in"]),
    ("IRS", ["irs"], ["irs.gov"]),
    # crypto
    ("Coinbase", ["coinbase"], ["coinbase.com"]),
    ("Binance", ["binance"], ["binance.com", "binance.us"]),
    ("Kraken", ["kraken"], ["kraken.com"]),
    ("MetaMask", ["metamask"], ["metamask.io"]),
    ("Ledger", ["ledger"], ["ledger.com"]),
    ("Trezor", ["trezor"], ["trezor.io"]),
    ("Blockchain.com", ["blockchain"], ["blockchain.com"]),
    # big tech & accounts
    ("Microsoft", ["microsoft", "outlook", "office365", "onedrive", "hotmail", "sharepoint"],
     ["microsoft.com", "microsoftonline.com", "microsoft365.com", "live.com", "outlook.com", "office.com",
      "office365.com", "hotmail.com", "onedrive.com", "sharepoint.com", "onmicrosoft.com", "windows.net",
      "azure.com", "bing.com", "xbox.com", "skype.com", "msn.com"]),
    ("Apple", ["apple", "icloud", "itunes"], ["apple.com", "icloud.com", "me.com", "itunes.com", "apple.news"]),
    ("Google", ["google", "gmail", "youtube"],
     ["google.com", "google.co.in", "google.co.uk", "google.de", "google.fr", "google.ca", "google.com.au",
      "google.co.jp", "gmail.com", "youtube.com", "youtu.be", "googleapis.com", "gstatic.com",
      "withgoogle.com", "goo.gl", "g.co", "blogger.com"]),
    ("Amazon", ["amazon", "aws"],
     ["amazon.com", "amazon.in", "amazon.co.uk", "amazon.de", "amazon.ca", "amazon.co.jp", "amazon.fr",
      "amazon.it", "amazon.es", "amazon.com.au", "amazonaws.com", "a2z.com", "amzn.to", "primevideo.com"]),
    ("Meta / Facebook", ["facebook", "meta"], ["facebook.com", "fb.com", "fb.me", "facebookmail.com", "meta.com"]),
    ("Instagram", ["instagram"], ["instagram.com"]),
    ("WhatsApp", ["whatsapp"], ["whatsapp.com", "whatsapp.net", "wa.me"]),
    ("Netflix", ["netflix"], ["netflix.com"]),
    ("LinkedIn", ["linkedin"], ["linkedin.com", "lnkd.in"]),
    ("X / Twitter", ["twitter"], ["twitter.com", "x.com", "t.co"]),
    ("Dropbox", ["dropbox"], ["dropbox.com", "dropboxusercontent.com"]),
    ("DocuSign", ["docusign"], ["docusign.com", "docusign.net"]),
    ("Adobe", ["adobe"], ["adobe.com"]),
    ("Yahoo", ["yahoo"], ["yahoo.com", "yahoo.co.jp"]),
    ("Salesforce", ["salesforce"], ["salesforce.com", "force.com"]),
    ("Okta", ["okta"], ["okta.com"]),
    ("Zoom", ["zoom"], ["zoom.us", "zoom.com"]),
    ("Slack", ["slack"], ["slack.com"]),
    ("GitHub", ["github"], ["github.com", "githubusercontent.com"]),
    ("Discord", ["discord"], ["discord.com", "discord.gg", "discordapp.com"]),
    ("Spotify", ["spotify"], ["spotify.com"]),
    ("Steam", ["steampowered", "steamcommunity"], ["steampowered.com", "steamcommunity.com"]),
    ("Roblox", ["roblox"], ["roblox.com"]),
    ("Epic Games", ["epicgames"], ["epicgames.com"]),
    # shopping & delivery
    ("eBay", ["ebay"], ["ebay.com", "ebay.co.uk", "ebay.de", "ebay.in"]),
    ("Walmart", ["walmart"], ["walmart.com"]),
    ("Flipkart", ["flipkart"], ["flipkart.com"]),
    ("Airbnb", ["airbnb"], ["airbnb.com"]),
    ("Uber", ["uber"], ["uber.com"]),
    ("DHL", ["dhl"], ["dhl.com", "dhl.de"]),
    ("FedEx", ["fedex"], ["fedex.com"]),
    ("UPS", ["ups"], ["ups.com"]),
    ("USPS", ["usps"], ["usps.com"]),
]
